version: "3.4"
services:
  api:
    image: rf-api:debug
    build:
      context: .
      target: rf-api-dev
    container_name: api
    volumes:
      - "./src:/usr/app/src:delegated"
      - /usr/node_modules
      - dbdata:/usr/app/src/database
    command: [ "npm", "run", "debug" ]
    # command: tail -f /dev/null

  mongodb1:
    image: mongo:4
    restart: always
    container_name: mongodb1
    volumes:
    - mongodata1:/data/db
    expose:
    - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]


volumes:
  dbdata: null
  mongodata1: